# Generated by Django 4.2.13 on 2024-08-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWalletTable',
            fields=[
                ('xpub', models.TextField(primary_key=True, serialize=False)),
                ('mnemonic', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('virtual_account', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('number_of_calls', models.IntegerField()),
                ('minutes_of_call_transfer', models.IntegerField()),
                ('customer_support_level', models.TextField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Single IVR', 'Single IVR'), ('Bulk IVR', 'Bulk IVR'), ('', 'None')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualAccountsTable',
            fields=[
                ('balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('currency', models.TextField(blank=True, null=True)),
                ('account_detail', models.TextField(blank=True, null=True)),
                ('account_id', models.TextField(primary_key=True, serialize=False)),
                ('wallet_address', models.TextField(blank=True, null=True)),
                ('derivation_index', models.TextField(blank=True, null=True)),
                ('deposit_address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='user.telegramuser')),
            ],
        ),
    ]
