# Generated by Django 4.2.13 on 2024-08-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccountstable',
            name='derivation_index',
        ),
        migrations.RemoveField(
            model_name='virtualaccountstable',
            name='wallet_address',
        ),
    ]
