# Generated by Django 4.2.13 on 2024-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_virtualaccountstable_derivation_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccountstable',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
