# Generated by Django 4.2.13 on 2024-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_virtualaccountstable_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwallettable',
            name='deposit_adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
