# Generated by Django 4.2.13 on 2024-08-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_mainwallettable_deposit_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainwallettable',
            old_name='deposit_adress',
            new_name='deposit_address',
        ),
        migrations.AddField(
            model_name='mainwallettable',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
