# Generated by Django 4.2.13 on 2024-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_deposit_adress_mainwallettable_deposit_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='price',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='plan_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
