# Generated by Django 4.2.13 on 2024-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_subscriptionplans_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwallettable',
            name='main_wallet_deposit_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
