# Generated by Django 4.2.13 on 2024-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_mainwallettable_main_wallet_deposit_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainwallettable',
            name='main_wallet_deposit_address',
        ),
        migrations.AddField(
            model_name='virtualaccountstable',
            name='main_wallet_deposit_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
