# Generated by Django 4.2.13 on 2024-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_mainwallettable_main_wallet_deposit_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='id',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='plan_id',
            field=models.UUIDField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
