# Generated by Django 4.2.13 on 2024-08-30 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_subscriptionplans_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='plan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
