# Generated by Django 4.2.13 on 2024-09-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_subscriptionplans_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='type',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
