# Generated by Django 4.2.13 on 2024-09-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_subscriptionplans_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplans',
            old_name='validity',
            new_name='validity_days',
        ),
    ]
