# Generated by Django 4.2.15 on 2024-09-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_subscriptionmodel'),
        ('payment', '0012_rename_validity_subscriptionplans_validity_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_status', models.CharField(default='inactive', max_length=50, null=True)),
                ('transfer_minutes_left', models.IntegerField(default=0, null=True)),
                ('bulk_ivr_calls_left', models.IntegerField(default=0, null=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user_plan', to='payment.subscriptionplans')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user_id', to='user.telegramuser')),
            ],
        ),
    ]
