# Generated by Django 4.2.13 on 2024-09-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_subscriptionmodel'),
        ('payment', '0013_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription_user_id', to='user.telegramuser'),
        ),
    ]
