# Generated by Django 4.2.13 on 2024-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_usersubscription_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_of_subscription',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
