# Generated by Django 4.2.13 on 2024-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_usersubscription_date_of_expiry_and_more'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='subscriptionplans',
#            name='minutes_of_call_transfer',
#            field=models.IntegerField(blank=True, null=True),
#        ),
#        migrations.AlterField(
#            model_name='subscriptionplans',
#            name='call_transfer',
#            field=models.BooleanField(default=False),
 #       ),
    ]
