# Generated by Django 4.2.13 on 2024-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_usersubscription_date_of_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplans',
            old_name='minutes_of_call_transfer',
            new_name='number_of_bulk_call_minutes',
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='number_of_bulk_call_minutes',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='call_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
