# Generated by Django 5.1.1 on 2024-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_subscriptionplans_minutes_of_call_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='minutes_of_call_transfer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='call_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
