# Generated by Django 4.2.13 on 2024-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_subscriptionplans_minutes_of_call_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='minutes_of_call_transfer',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='transfer_minutes_left',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='call_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
