# Generated by Django 4.2.13 on 2024-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_remove_subscriptionplans_minutes_of_call_transfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerWalletTable',
            fields=[
                ('address', models.TextField(primary_key=True, serialize=False)),
                ('currency', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mainwallettable',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
