# Generated by Django 4.2.13 on 2024-10-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_ownerwallettable_mainwallettable_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
