# Generated by Django 4.2.13 on 2024-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_usersubscription_auto_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='validity_days',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
