# Generated by Django 4.2.13 on 2024-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_subscriptionplans_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='single_ivr_flow',
            field=models.IntegerField(blank=True, default=2147483647, null=True),
        ),
    ]
