# Generated by Django 4.2.13 on 2024-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_subscriptionplans_single_ivr_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='single_ivr_flow',
            field=models.IntegerField(default=2147483647),
        ),
    ]
