# Generated by Django 4.2.13 on 2024-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_subscriptionplans_single_ivr_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='number_of_bulk_call_minutes',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='bulk_ivr_calls_left',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
