# Generated by Django 4.2.13 on 2024-10-15 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_telegramuser_free_gift_single_ivr'),
        ('payment', '0025_alter_subscriptionplans_number_of_bulk_call_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionLogs',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('SUB', 'Subscription'), ('OVR', 'Overage'), ('WDR', 'Withdrawal'), ('DEP', 'Deposit'), ('TRF', 'Transfer')], default='SUB', max_length=3)),
                ('transaction_date', models.DateField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='user.telegramuser')),
            ],
        ),
    ]
