# Generated by Django 4.2.13 on 2024-10-16 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_usertransactionlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OveragePricingTable',
            fields=[
                ('ovr_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('overage_pricing_per_minute', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
    ]
