# Generated by Django 4.2.13 on 2024-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_overagepricingtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overagepricingtable',
            old_name='overage_pricing_per_minute',
            new_name='overage_pricing',
        ),
        migrations.AddField(
            model_name='overagepricingtable',
            name='pricing_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
