# Generated by Django 4.2.13 on 2024-10-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_rename_overage_pricing_per_minute_overagepricingtable_overage_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overagepricingtable',
            name='pricing_unit',
            field=models.CharField(choices=[('MIN', 'Minutes'), ('SEC', 'Seconds'), ('HRS', 'Hours')], default='MIN', max_length=3),
        ),
    ]
