# Generated by Django 4.2.13 on 2024-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_alter_overagepricingtable_pricing_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overagepricingtable',
            name='ovr_id',
        ),
        migrations.AlterField(
            model_name='overagepricingtable',
            name='pricing_unit',
            field=models.CharField(choices=[('MIN', 'Minutes'), ('SEC', 'Seconds'), ('HRS', 'Hours')], default='MIN', max_length=3, primary_key=True, serialize=False),
        ),
    ]
