# Generated by Django 4.2.13 on 2024-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_remove_overagepricingtable_ovr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='single_ivr_left',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='single_ivr_flow',
            field=models.DecimalField(decimal_places=6, default=2147483647, max_digits=20),
        ),
    ]
