# Generated by Django 4.2.13 on 2024-10-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_usersubscription_single_ivr_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplans',
            old_name='single_ivr_flow',
            new_name='single_ivr_minutes',
        ),
    ]
