# Generated by Django 4.2.13 on 2024-10-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_telegramuser_free_gift_single_ivr'),
        ('payment', '0032_rename_single_ivr_flow_subscriptionplans_single_ivr_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageFreePlanSingleIVRCall',
            fields=[
                ('minutes_left', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('call_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pathway_id', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manage_free_plans', to='user.telegramuser')),
            ],
        ),
    ]
