# Generated by Django 4.2.13 on 2024-10-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_managefreeplansingleivrcall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managefreeplansingleivrcall',
            old_name='minutes_left',
            new_name='call_duration',
        ),
    ]
