# Generated by Django 4.2.13 on 2024-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_rename_minutes_left_managefreeplansingleivrcall_call_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='managefreeplansingleivrcall',
            name='call_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='managefreeplansingleivrcall',
            name='pathway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
