# Generated by Django 4.2.13 on 2024-10-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_managefreeplansingleivrcall_call_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managefreeplansingleivrcall',
            name='call_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
