# Generated by Django 4.2.13 on 2024-10-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_managefreeplansingleivrcall_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwallettable',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
