# Generated by Django 4.2.13 on 2024-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0038_alter_mainwallettable_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwallettable',
            name='gas_limit',
            field=models.CharField(default='40000', max_length=100),
        ),
        migrations.AddField(
            model_name='mainwallettable',
            name='gas_price',
            field=models.CharField(default='20', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainwallettable',
            name='fee',
            field=models.DecimalField(decimal_places=6, default=1e-05, max_digits=20),
        ),
    ]
