# Generated by Django 4.2.13 on 2024-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_mainwallettable_gas_limit_mainwallettable_gas_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactionlogs',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
