# Generated by Django 4.2.13 on 2024-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0040_alter_usertransactionlogs_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactionlogs',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
