# Generated by Django 4.2.13 on 2024-12-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20241121_1435'),
        ('payment', '0041_alter_usertransactionlogs_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user_id', to='user.telegramuser'),
        ),
    ]
