# Generated by Django 4.2.13 on 2024-12-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0042_alter_usersubscription_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="plan_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_user_plan",
                to="payment.subscriptionplans",
            ),
        ),
    ]
