# Generated by Django 4.2.13 on 2025-01-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20241121_1435"),
        ("payment", "0043_alter_usersubscription_plan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTMF_Inbox",
            fields=[
                ("call_id", models.TextField(primary_key=True, serialize=False)),
                ("call_number", models.TextField()),
                ("pathway_id", models.TextField(null=True)),
                ("timestamp", models.BigIntegerField()),
                ("dtmf_input", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dtmf_inbox",
                        to="user.telegramuser",
                    ),
                ),
            ],
        ),
    ]
