# Generated by Django 4.2.13 on 2025-01-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0044_dtmf_inbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtmf_inbox",
            name="timestamp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
