# Generated by Django 4.2.13 on 2025-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0045_alter_dtmf_inbox_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtmf_inbox",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
