# Generated by Django 4.2.13 on 2025-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0046_alter_dtmf_inbox_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtmf_inbox",
            name="dtmf_input",
            field=models.TextField(blank=True, null=True),
        ),
    ]
