# Generated by Django 4.2.13 on 2025-02-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0047_alter_dtmf_inbox_dtmf_input"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainWalletTable",
        ),
        migrations.DeleteModel(
            name="VirtualAccountsTable",
        ),
    ]
