# Generated by Django 4.2.13 on 2025-02-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20241121_1435"),
        ("payment", "0048_delete_mainwallettable_delete_virtualaccountstable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managefreeplansingleivrcall",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manage_free_plans",
                to="user.telegramuser",
            ),
        ),
    ]
