# Generated by Django 4.2.13 on 2026-02-16 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_telegramuser_customer_id_and_more"),
        ("payment", "0049_alter_managefreeplansingleivrcall_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransactionlogs",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("SUB", "Subscription"),
                    ("OVR", "Overage"),
                    ("WDR", "Withdrawal"),
                    ("DEP", "Deposit"),
                    ("TRF", "Transfer"),
                    ("RFD", "Refund"),
                ],
                default="SUB",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("SUB", "Subscription"),
                            ("OVR", "Overage"),
                            ("WDR", "Withdrawal"),
                            ("DEP", "Deposit"),
                            ("TRF", "Transfer"),
                            ("RFD", "Refund"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="user.telegramuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
