# Generated by Django 4.2.13 on 2026-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0050_alter_usertransactionlogs_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransactionlogs",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("SUB", "Subscription"),
                    ("OVR", "Overage"),
                    ("WDR", "Withdrawal"),
                    ("DEP", "Deposit"),
                    ("TRF", "Transfer"),
                    ("RFD", "Refund"),
                    ("REC", "Recording"),
                ],
                default="SUB",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("SUB", "Subscription"),
                    ("OVR", "Overage"),
                    ("WDR", "Withdrawal"),
                    ("DEP", "Deposit"),
                    ("TRF", "Transfer"),
                    ("RFD", "Refund"),
                    ("REC", "Recording"),
                ],
                max_length=3,
            ),
        ),
    ]
