# Generated by Django 4.2.13 on 2024-08-27 08:25

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('call_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CallLogsTable',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('call_number', models.TextField()),
                ('pathway_id', models.TextField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('feedback_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('feedback_answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLogs',
            fields=[
                ('pathway_id', models.TextField(primary_key=True, serialize=False)),
                ('feedback_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pathways',
            fields=[
                ('pathway_id', models.TextField(primary_key=True, serialize=False)),
                ('pathway_name', models.TextField()),
                ('pathway_user_id', models.BigIntegerField()),
                ('pathway_description', models.TextField(null=True)),
                ('pathway_payload', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferCallNumbers',
            fields=[
                ('user_id', models.BigIntegerField()),
                ('phone_number', models.TextField()),
                ('num_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
