# Generated by Django 5.0.7 on 2024-07-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathways',
            fields=[
                ('pathway_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pathway_name', models.TextField()),
                ('pathway_user_id', models.BigIntegerField()),
            ],
        ),
    ]
