# Generated by Django 5.0.7 on 2024-07-17 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('pathway_id', models.TextField()),
                ('node_name', models.CharField(max_length=255)),
                ('node_id', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathways',
            fields=[
                ('pathway_id', models.TextField(primary_key=True, serialize=False)),
                ('pathway_name', models.TextField()),
                ('pathway_user_id', models.BigIntegerField()),
                ('pathway_description', models.TextField(null=True)),
                ('pathway_payload', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferCallNumbers',
            fields=[
                ('user_id', models.BigIntegerField()),
                ('phone_number', models.TextField()),
                ('num_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
