# Generated by Django 4.2.13 on 2024-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDuration',
            fields=[
                ('call_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pathway_id', models.CharField(max_length=255)),
                ('duration_in_seconds', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('queue_status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
