# Generated by Django 5.0.7 on 2024-07-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathways',
            name='pathway_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
