# Generated by Django 5.0.7 on 2024-07-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
