# Generated by Django 4.2.13 on 2024-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_callduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogstable',
            name='call_status',
            field=models.TextField(null=True),
        ),
    ]
