# Generated by Django 4.2.13 on 2024-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_delete_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('call_details', models.TextField()),
                ('call_number', models.TextField()),
            ],
        ),
    ]
