# Generated by Django 4.2.13 on 2024-08-12 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_calllogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('call_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLogs',
            fields=[
                ('pathway_id', models.TextField(primary_key=True, serialize=False)),
                ('feedback_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='calllogs',
            name='call_details',
        ),
    ]
