# Generated by Django 4.2.13 on 2024-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_calllogstable_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='callduration',
            name='remaining_calls_left_after_subtraction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
