# Generated by Django 4.2.13 on 2024-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_calldetails_feedbacklogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogs',
            name='pathway_id',
            field=models.TextField(null=True),
        ),
    ]
