# Generated by Django 4.2.13 on 2024-10-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_callduration_remaining_calls_left_after_subtraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callduration',
            old_name='remaining_calls_left_after_subtraction',
            new_name='additional_minutes',
        ),
    ]
