# Generated by Django 4.2.13 on 2024-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_calllogs_pathway_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogs',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
