# Generated by Django 5.0.7 on 2024-07-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_pathways_pathway_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathways',
            name='pathway_description',
        ),
    ]
