# Generated by Django 4.2.13 on 2024-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_remaining_calls_left_after_subtraction_callduration_additional_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='callduration',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
