# Generated by Django 5.0.7 on 2024-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_pathways_pathway_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathways',
            name='pathway_name',
            field=models.TextField(null=True),
        ),
    ]
