# Generated by Django 4.2.13 on 2024-08-12 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_calllogs_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('feedback_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('feedback_answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
        ),
    ]
