# Generated by Django 5.0.7 on 2024-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_pathways_pathway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathways',
            name='pathway_name',
            field=models.TextField(),
        ),
    ]
