# Generated by Django 4.2.13 on 2024-08-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_feedbackdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallLogs',
            new_name='CallLogsTable',
        ),
    ]
