# Generated by Django 4.2.13 on 2024-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_callduration_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='callduration',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
