# Generated by Django 4.2.13 on 2024-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_callduration_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCallLogs',
            fields=[
                ('call_id', models.TextField(primary_key=True, serialize=False)),
                ('batch_id', models.TextField()),
                ('pathway_id', models.TextField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
