# Generated by Django 5.0.7 on 2024-07-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_pathways_pathway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathways',
            name='pathway_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pathways',
            name='pathway_payload',
            field=models.TextField(null=True),
        ),
    ]
