# Generated by Django 5.0.7 on 2024-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_pathways_pathway_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathways',
            name='pathway_payload',
        ),
        migrations.AddField(
            model_name='pathways',
            name='pathway_edges',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pathways',
            name='pathway_nodes',
            field=models.TextField(null=True),
        ),
    ]
