# Generated by Django 4.2.13 on 2024-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_batchcalllogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcalllogs',
            name='from_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchcalllogs',
            name='to_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
