# Generated by Django 5.0.7 on 2024-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_pathways_pathway_payload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathways',
            name='pathway_edges',
        ),
        migrations.RemoveField(
            model_name='pathways',
            name='pathway_nodes',
        ),
        migrations.AddField(
            model_name='pathways',
            name='pathway_payload',
            field=models.TextField(null=True),
        ),
    ]
