# Generated by Django 4.2.13 on 2025-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0011_batchcalllogs_call_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllogstable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
