# Generated by Django 4.2.13 on 2025-01-23 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0012_calllogstable_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
    ]
