# Generated by Django 4.2.13 on 2025-01-30 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0013_frequentlyaskedquestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task", models.TextField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="pathways",
            name="dtmf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pathways",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
