# Generated by Django 4.2.13 on 2025-01-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0014_tasks_pathways_dtmf_pathways_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
