# Generated by Django 4.2.13 on 2025-01-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0015_tasks_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="AI_Assisted_Tasks",
        ),
    ]
