# Generated by Django 4.2.13 on 2025-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0016_rename_tasks_ai_assisted_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ai_assisted_tasks",
            old_name="task",
            new_name="task_description",
        ),
        migrations.AddField(
            model_name="ai_assisted_tasks",
            name="task_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
