# Generated by Django 4.2.13 on 2025-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0017_rename_task_ai_assisted_tasks_task_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallerIds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caller_id", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
