# Generated by Django 4.2.13 on 2025-02-11 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0018_callerids"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignLogs",
            fields=[
                (
                    "campaign_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_calls", models.IntegerField(blank=True, null=True)),
                ("avg_call_duration", models.FloatField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
