# Generated by Django 4.2.13 on 2025-02-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20241121_1435"),
        ("bot", "0019_campaignlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlogs",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_user",
                to="user.telegramuser",
            ),
        ),
    ]
