# Generated by Django 4.2.13 on 2025-02-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20241121_1435"),
        ("bot", "0020_campaignlogs_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledCalls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.TextField()),
                ("schedule_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_call_user",
                        to="user.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Remindertable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.TextField()),
                ("reminder_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_user",
                        to="user.telegramuser",
                    ),
                ),
            ],
        ),
    ]
