# Generated by Django 4.2.13 on 2025-02-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0021_scheduledcalls_remindertable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remindertable",
            name="batch_id",
        ),
        migrations.RemoveField(
            model_name="scheduledcalls",
            name="batch_id",
        ),
        migrations.AddField(
            model_name="remindertable",
            name="campaign_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminder_campaign_log",
                to="bot.campaignlogs",
            ),
        ),
        migrations.AddField(
            model_name="scheduledcalls",
            name="campaign_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_call_log",
                to="bot.campaignlogs",
            ),
        ),
    ]
