# Generated by Django 4.2.13 on 2025-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0022_remove_remindertable_batch_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcalls",
            name="call_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
