# Generated by Django 4.2.13 on 2025-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0024_scheduledcalls_caller_id_scheduledcalls_pathway_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcalls",
            name="call_status",
            field=models.BooleanField(default=False),
        ),
    ]
