# Generated by Django 4.2.13 on 2025-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0025_scheduledcalls_call_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlogs",
            name="batch_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
