# Generated by Django 4.2.13 on 2025-02-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0026_campaignlogs_batch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcalls",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
