# Generated by Django 4.2.13 on 2025-02-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0027_scheduledcalls_canceled"),
    ]

    operations = [
        migrations.AddField(
            model_name="remindertable",
            name="scheduled_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="bot.scheduledcalls",
            ),
        ),
        migrations.AddField(
            model_name="remindertable",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
