# Generated by Django 4.2.13 on 2026-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0028_remindertable_scheduled_call_remindertable_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveCall",
            fields=[
                (
                    "call_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.BigIntegerField()),
                ("to_number", models.CharField(max_length=255)),
                (
                    "from_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("region", models.CharField(default="US/Canada", max_length=100)),
                (
                    "rate_per_minute",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("call_type", models.CharField(default="single", max_length=20)),
                ("billing_source", models.CharField(default="plan", max_length=20)),
                ("start_time", models.DateTimeField()),
                ("last_billed_at", models.DateTimeField()),
                (
                    "total_billed",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("warning_sent", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="bot_activec_is_acti_1533f4_idx"
                    )
                ],
            },
        ),
    ]
