# Generated by Django 4.2.13 on 2026-02-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_telegramuser_customer_id_and_more"),
        ("bot", "0029_activecall"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50, unique=True)),
                ("country_code", models.CharField(default="US", max_length=5)),
                ("area_code", models.IntegerField(blank=True, null=True)),
                ("is_toll_free", models.BooleanField(default=False)),
                ("nickname", models.CharField(blank=True, default="", max_length=100)),
                (
                    "monthly_cost",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("next_renewal_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="user.telegramuser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="bot_userpho_user_id_99723f_idx",
                    )
                ],
            },
        ),
    ]
