# Generated by Django 4.2.13 on 2026-02-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_telegramuser_customer_id_and_more"),
        ("bot", "0030_userphonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPhoneNumberPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(default="US", max_length=5)),
                ("area_code", models.IntegerField(blank=True, null=True)),
                ("is_toll_free", models.BooleanField(default=False)),
                (
                    "monthly_cost",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("is_failed", models.BooleanField(default=False)),
                ("failure_reason", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_purchases",
                        to="user.telegramuser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_fulfilled"],
                        name="bot_pending_user_id_62516b_idx",
                    )
                ],
            },
        ),
    ]
