# Generated by Django 4.2.13 on 2026-02-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_telegramuser_customer_id_and_more"),
        ("bot", "0031_pendingphonenumberpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="userphonenumber",
            name="forwarding_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="forwarding_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="voicemail_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="voicemail_message",
            field=models.TextField(
                blank=True,
                default="Please leave a message after the tone. We will get back to you shortly.",
            ),
        ),
        migrations.CreateModel(
            name="PendingDTMFApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.CharField(max_length=255)),
                ("user_id", models.BigIntegerField()),
                ("digits", models.CharField(max_length=50)),
                ("node_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["call_id", "status"],
                        name="bot_pending_call_id_88ee16_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SMSInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                ("from_number", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_inbox",
                        to="user.telegramuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="bot_smsinbo_user_id_10e3ac_idx",
                    )
                ],
            },
        ),
    ]
