# Generated by Django 4.2.13 on 2026-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0032_userphonenumber_forwarding_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userphonenumber",
            name="business_hours_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="business_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="business_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="business_hours_timezone",
            field=models.CharField(blank=True, default="US/Eastern", max_length=50),
        ),
    ]
