# Generated by Django 4.2.13 on 2026-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0033_userphonenumber_business_hours_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchcalllogs",
            name="recording_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calllogstable",
            name="recording_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="calllogstable",
            name="recording_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "call_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.BigIntegerField()),
                ("batch_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "retell_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("downloaded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="bot_callrec_user_id_8894cc_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="bot_callrec_batch_i_7104ba_idx"
                    ),
                ],
            },
        ),
    ]
