# Generated by Django 4.2.13 on 2026-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0034_batchcalllogs_recording_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrecording",
            name="call_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="transcript_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="user_sentiment",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
