# Generated by Django 4.2.13 on 2024-08-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('language', models.CharField(default='English', max_length=50, null=True)),
                ('plan', models.CharField(max_length=50, null=True)),
                ('subscription_status', models.CharField(default='inactive', max_length=50, null=True)),
                ('free_gift_single_ivr', models.BooleanField(default=True)),
                ('free_gift_bulk_ivr', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_plan', models.CharField(max_length=50)),
                ('subscription_status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='user.telegramuser')),
            ],
        ),
    ]
