# Generated by Django 4.2.15 on 2024-09-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionModel',
        ),
    ]
