# Generated by Django 5.0.7 on 2024-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
