# Generated by Django 4.2.13 on 2024-09-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_subscriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='free_gift_bulk_ivr',
        ),
    ]
