# Generated by Django 5.0.7 on 2024-07-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
