# Generated by Django 5.0.7 on 2024-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_telegramuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='plan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
