# Generated by Django 4.2.13 on 2024-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_telegramuser_free_gift_bulk_ivr'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='free_plan',
            field=models.BooleanField(default=True),
        ),
    ]
