# Generated by Django 5.0.7 on 2024-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_telegramuser_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscription_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
