# Generated by Django 4.2.13 on 2024-10-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_telegramuser_free_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='free_gift_single_ivr',
        ),
    ]
