# Generated by Django 4.2.13 on 2024-11-12 13:15

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_telegramuser_free_gift_single_ivr'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
