# Generated by Django 4.2.13 on 2024-11-15 10:12

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_telegramuser_customer_id_telegramuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
    ]
