# Generated by Django 4.2.13 on 2024-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_telegramuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
