# Generated by Django 4.2.13 on 2024-11-21 13:45

from django.db import migrations




from django.db import migrations
from django.contrib.auth.models import User


def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    username = 'admin'
    email = ''
    password = 'speechcadadmin1234'

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(username=username, email=email, password=password)
        print(f"Superuser created: username={username}, password={password}")
    else:
        print("Superuser already exists. No action taken.")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_telegramuser_plan'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]