# Generated by Django 4.2.13 on 2026-02-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20241121_1435"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="token",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
