# Generated by Django 4.2.13 on 2026-02-16 15:23

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_telegramuser_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="customer_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="token",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=500, null=True)
            ),
        ),
    ]
