# Generated by Django 4.2.13 on 2026-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_telegramuser_customer_id_telegramuser_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="token",
        ),
    ]
