# Generated by Django 4.2.13 on 2026-02-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_telegramuser_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
