# Generated by Django 4.2.13 on 2026-02-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_telegramuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
