from psycopg2.extensions import TRANSACTION_STATUS_IDLE

SINGLE_CALLS_LEFT = "Single IVR Calls left : "
UNPAID_MINUTES_PROMPT = "You have unpaid additional minutes. Please settle the charges before proceeding."
WALLET_DETAILS_ERROR = "Error fetching wallet details!"
WALLET_BALANCE = "You have the following balance in your wallet:"
SUBSCRIPTION_VERIFIED ="Subscription verified. 📞"
ACTIVATE_SUBSCRIPTION = "A single IVR call requires an active subscription. Please activate your subscription to proceed."
OUTGOING_CONNECTIONS_MISSING = "The following nodes do not have any outgoing connections to other nodes: "
INCOMING_CONNECTIONS_MISSING = "The following nodes do not connect to any other nodes: "
ADD_ONE_EDGE = "At least, add one edge for the missing nodes!"
NO_VARIABLES_FOUND = "No variables found for call ID:"
EMAIL_PROMPT = "Please enter your email address:"
INVALID_EMAIL_FORMAT = "Invalid email format. Please enter a valid email address:"
MOBILE_NUMBER_PROMPT = "Please enter your mobile number:"
INVALID_NUMBER_PROMPT = "Invalid mobile number format. Please enter a valid mobile number:"
REQUEST_FAILED = "Request failed due to the following issue:"
ACTION_CANCELLED = "You have cancelled the current action."
MAIN_MENU_REDIRECTION = "Redirecting you to the main menu!"
SUBSCRIPTION_PLAN_OPTIONS = "Now, let’s get you on the right plan. Please choose a subscription plan from the options below:"
DURATION_SELECTION_PROMPT = "How long would you like to subscribe? Select your preferred duration:"
NO_BULK_MINS_LEFT = "No Bulk IVR Calls"
PLAN_SELECTED = "You’ve selected the following plan."
SUCCESSFUL_FREE_TRIAL_ACTIVATION = "You have successfully activated your free trial!"
AUTO_RENEWAL_PROMPT = "Would you like to enable auto-renewal from your wallet balance?"
FULL_NODE_ACCESS = 'Full Node Access'
PARTIAL_NODE_ACCESS = 'Partial Node Access'
CALL_TRANSFER_INCLUDED = 'Call Transfer Included'
CALL_TRANSFER_EXCLUDED = 'Call Transfer Excluded'
TOP_UP_PROMPT = 'Please select a payment method to top up your balance:'
SUBSCRIPTION_PAYMENT_METHOD_PROMPT = 'Please confirm your payment method to proceed:'
USER_INFORMATION_NOT_FOUND = 'User information not found!'
MAIN_MENU_PROMPT = 'Here is the main menu:'
SUBSCRIPTION_ACTIVATED = 'Subscription activated!'
PAYMENT_SUCCESSFUL = 'Payment successful! ✅'
RECEIVERS_WALLET_NOT_FOUND = "The receiver's wallet could not be found."
PROCESSING_PAYMENT = "We are processing your payment, please wait..."
CURRENT_BALANCE = 'Your current balance is'
VIRTUAL_ACCOUNT_NOT_FOUND = 'Account Not Found!'
INVOICE_REVIEW_PROMPT = 'Please review the invoice for your selected subscription plan:'
PLAN_DOESNT_EXIST = 'Sorry, the selected plan does not exist anymore!'
DAYS = 'Days'
DAY = 'Day'
VALIDITY_PROMPT = 'Select validity for your plan:'
PLAN_VALIDITY = 'subscription plans with different validity:'
VALIDITY = 'Validity:'
SUBSCRIPTION_PLAN_SELECTION_PROMPT = 'Please select a subscription plan below:'
NAME_INPUT_PROMPT = 'What’s your name? Let’s personalize your experience! (e.g., Ren)'
SETUP_WELCOME = "Welcome to Speechcad IVR Bot!"
SETUP_PROMPT = ("We’re thrilled to have you here! 🎉 \n"
                "Let’s get you started so you can explore all the exciting features we offer. 🌟 \n"
                "This setup is quick and easy—let's dive in! 🚀")
EXISTING_USER_WELCOME = "Welcome! 🎉 We are glad to have you again. 🎉 Here is the main menu!"
NEW_USER_WELCOME = "Welcome! As a new user! 🎉"
PROFILE_LANGUAGE_SELECTION_PROMPT = "To ensure everything is in your preferred language, please select one below:"
LANGUAGE_SELECTION_PROMPT = "Select your preferred language:"
USERNAME_PROMPT = "Your username is"
SETUP_TOOLTIP = 'The setup is fast and easy. You’ll be ready in just a few steps!'
ACKNOWLEDGE_AND_PROCEED = 'Acknowledge and Proceed ✅'
NODE_TYPE_SELECTION_PROMPT = 'Select the type of node:'
TRANSCRIPT_NOT_FOUND = 'No transcript found for this call.'
VIEW_TRANSCRIPT_PROMPT = 'Select a call to view the transcript:'
CALL_LOGS_NOT_FOUND = 'No call logs found for your user ID.'
VIEW_VARIABLES_PROMPT = 'Select a call to view variables:'
EDGES_DELETED = "Node and its associated edges have been deleted successfully."
BALANCE_IN_USD = "Your Wallet balance is "
NICE_TO_MEET_YOU = "Nice to meet you,"
PROFILE_SETTING_PROMPT = ("We’re setting up your account now. "
                          "Please hold on for just a moment while we finalize the details.")
FREE_TRIAL_TOOLTIP = "Enjoy premium features during your free trial period!"
SETUP_COMPLETION_FIRST_HALF = "✨ Great news! Your account is ready! 🎉 Your username is "
SETUP_COMPLETION_SECOND_HALF = " and even better, you’re eligible for a free trial! 💃🎉"
ACCOUNT_SETUP_TOOLTIP = "We’re doing the work behind the scenes. Just follow the steps!"
base_url = 'https://api.bland.ai'
invalid_data = 'Invalid Data!'
error = 'Error! '
PROCESSING_ERROR = 'We were unable to process your request due to the following error:'
DEPOSIT_SUCCESSFUL = 'Deposit successful! ✅ '
INSUFFICIENT_DEPOSIT_AMOUNT = 'Insufficient amount to activate subscription.'
WEBHOOK_RECEIVED = 'Webhook received successfully'
INVALID_JSON = 'Invalid JSON data'
WEBHOOK_DEPOSIT = 'webhook_deposit'
WEBHOOK = 'webhook'
INSUFFICIENT_BALANCE = 'Insufficient balance. Please top up your wallet or select another payment method. ⚠️'
DEPOSIT_ADDRESS = 'Get Deposit Address'
PAYMENT_METHOD_PROMPT = 'How would you like to make payment for your subscription?'
AVAILABLE_COMMANDS_PROMPT = 'Here are the available commands:'
SUBSCRIPTION_PLAN = 'Subscription Plan'
NAME = 'Name'
BULK_IVR_LEFT = 'Number of Bulk IVR call minutes left'
CALL_TRANSFER_NODE = 'Call Transfer Node'
WALLET_INFORMATION = 'Your wallet information is as follows:'
PROFILE_INFORMATION_PROMPT = 'Here is your profile information:'
USERNAME = 'Username'
NO_SUBSCRIPTION_PLAN = 'No Subscription Plan!'
JOIN_CHANNEL_PROMPT = 'Join our channel for updates and support:'
INACTIVE = 'inactive'
BULK_IVR_SUBSCRIPTION_PROMPT = 'A Bulk IVR call requires an active subscription. Please activate your subscription to proceed.'
ACTIVE_SUBSCRIPTION_PLAN_PROMPT = 'You are currently assigned to the following subscription plan:'
SUBSCRIPTION_PLAN_NOT_FOUND = 'Subscription Plan not found!'
CHECKING_WALLETS = 'Checking your wallets...'
PLAN_NAME = 'Plan Name:'
PRICE = 'Price:'
FEATURES = 'Features:'
CUSTOMER_SUPPORT_LEVEL = 'Customer Support Level'
DAY_PLAN = 'Day Plan'
UNLIMITED_SINGLE_IVR = 'Unlimited Single IVR calls'
BULK_IVR_CALLS = 'Bulk IVR call minutes'
CALL_TRANSFER_MINS = 'Minutes of Call Transfer'
SELECTION_PROMPT = 'Select from the following options:'
WELCOME_PROMPT = 'Welcome to the Main Menu!'
PATHWAY_NOT_FOUND = 'Pathway not found!'
NOT_FOUND = 'not found!'
ACCOUNT_CREATED_SUCCESSFULLY = 'Account Created successfully!'
YES = "Yes"
NO = "No"
WALLET = 'Wallet'
TOP_UP = 'Top Up Wallet 💳'
BACK = 'Back'
back = 'back'
AUTO_RENEWAL_ENABLED = "Auto-renewal has been enabled."
PROCEED_PAYMENT= "Please proceed with payment."
AUTO_RENEWAL_DISABLED = "Auto-renewal has been disabled"
WALLET_BALANCE_PAYMENT = "Pay from Wallet Balance"
CRYPTO_PAYMENT = "Pay with Cryptocurrency"
UNSUPPORTED_CURRENCY = "Unsupported Currency"
TOP_UP_AMOUNT_PROMPT = "Enter the amount to top up your wallet: "
SCAN_ADDRESS_PROMPT = "Scan this QR code or use the address below to complete the payment:"
AMOUNT_NEEDED = "Amount needed for subscription:"
AMOUNT_DEPOSITED = "Amount Deposited: "
TABLE_UPDATE_FAILED = "Failed to update user tables due to the following issue:"
MISSING_KEY = "Missing key:"
METHOD_NOT_ALLOWED = "Method Not Allowed"
TRANSACTION_ID = "Transaction id:"
PAYMENT_STATUS =  "Payment status:"
USER_ID = "User id:"
PAID_AMOUNT = "Paid Amount:"
PAID_CURRENCY = "Paid Currency:"
TRANSACTION_DETAILS = "Transaction Details:"
TOP_UP_SUCCESSFUL = 'Top Up successful! ✅ '
SETUP_COMPLETE = "Your account setup is complete! You can now explore all the features of the Speechcad IVR Bot. Let's get started!"





